/* Rostom Immobilier — EN/FR/AR translations stored per user */
const LANG_KEY = 'rostomLanguageV1';
const DEFAULT_LANG = 'en';

const I18N = {
  en: {
    'nav.home':'Home','nav.properties':'Properties','nav.houses':'Houses','nav.apartments':'Apartments','nav.contact':'Contact','nav.menu':'Menu','nav.close':'Close','nav.lang':'Language','nav.cta':'Book a visit',
    'hero.kicker':'Batna · All Algeria','hero.buy':'Buy.','hero.sell':'Sell.','hero.rent':'Rent.','hero.title':'Curated properties for modern living','hero.lead':'A clean real estate showcase for homes, villas, apartments, land and commercial spaces across Algeria.','hero.view':'Explore properties','hero.about':'About Rostom','hero.cardTitle':'69 wilayas','hero.cardText':'Wilaya and Baladiya dropdowns are ready for Algeria. Batna includes popular areas like Bouaakal and Douar Eddis too.',
    'search.status':'Status','search.wilaya':'Wilaya','search.commune':'Baladiya / area','search.query':'Search','search.all':'All','search.allAlgeria':'All Algeria','search.allAreas':'All areas','search.placeholder':'Batna, villa, land...','search.go':'Search',
    'stats.properties':'Properties','stats.years':'Years','stats.wilayas':'Wilayas','stats.contacts':'Fast contact','section.featured.kicker':'Featured properties','section.featured.title':'Selected listings','section.featured.sub':'Fresh, clean cards with useful information only. Empty fields stay hidden automatically.','section.featured.all':'View all',
    'section.categories.kicker':'Categories','section.categories.title':'Find what you need faster','cat.houses':'Houses','cat.housesDesc':'Family houses, duplexes and residential buildings.','cat.apartments':'Apartments','cat.apartmentsDesc':'F2, F3, high standing, sale and rent.','cat.villas':'Villas','cat.villasDesc':'Premium villas, gardens, garages and large surfaces.','cat.estates':'All properties','cat.estatesDesc':'Land, offices, shops, projects and more.',
    'section.about.kicker':'Why Rostom','section.about.title':'Simple website. Strong trust.','section.about.sub':'Real estate clients usually want three things: clear photos, clear price, and an easy way to contact you.','about.one':'No account needed for visitors.','about.two':'Filters by status, category, wilaya and baladiya.','about.three':'Each card feels modern, alive and easy to scan.','about.four':'Ready to connect later with WhatsApp, email or a real database.',
    'process.kicker':'Process','process.title':'How visitors move from looking to calling','process.1':'Discover needs','process.1d':'They filter by location, type and status.','process.2':'Explore properties','process.2d':'They open a property and check photos/details.','process.3':'Ask for visit','process.3d':'They contact you without signing up.','process.4':'Close the deal','process.4d':'You continue the work outside the website.',
    'page.properties.title':'All properties','page.properties.sub':'Filter quickly by status, category, wilaya and baladiya.','page.houses.title':'Houses','page.houses.sub':'All houses published by Rostom Immobilier.','page.apartments.title':'Apartments','page.apartments.sub':'Apartment sales and rentals across Algeria.','page.villas.title':'Villas','page.villas.sub':'Modern villas, premium homes and large surfaces.','page.about.title':'A clear, modern and credible agency.','page.about.sub':'The goal is simple: make people trust you quickly.','page.contact.title':'Tell us what you need.','page.contact.sub':'Call, WhatsApp, or send a simple request.',
    'filter.category':'Category','filter.quick':'Quick','filter.sale':'Sale','filter.rent':'Rent','filter.new':'New project','filter.allCat':'All categories','filter.searchPlaceholder':'Title, city, keyword...','filter.areaDisabled':'Choose wilaya first',
    'card.details':'Explore','card.tour':'360° tour','card.contact':'Contact','card.forSale':'For sale','card.forRent':'For rent','card.new':'New project','card.surface':'m²','card.land':'Land','card.rooms':'rooms','card.bedrooms':'bed.','card.baths':'bath','card.floor':'Floor','empty':'No property found. Try another filter.',
    'detail.description':'Description','detail.features':'Features','detail.type':'Type','detail.status':'Status','detail.wilaya':'Wilaya','detail.commune':'Baladiya / area','detail.address':'Address','detail.price':'Price','detail.surface':'Built area','detail.land':'Land area','detail.rooms':'Rooms','detail.bedrooms':'Bedrooms','detail.bathrooms':'Bathrooms','detail.floor':'Floor','detail.year':'Year','detail.phone':'Phone','detail.visit':'Ask for visit','detail.call':'Call','detail.notFound':'This property cannot be found.','detail.virtualTour':'360 virtual tour','detail.tourStart':'View 360 tour','detail.tourHelp':'Drag to look around. On phone, move with your finger.','detail.tourExternal':'Open virtual tour','detail.tourRoom':'Room',
    'contact.name':'Name','contact.phone':'Phone','contact.subject':'Subject','contact.message':'Message','contact.send':'Send request','contact.buy':'Buy a property','contact.rent':'Rent a property','contact.sell':'Sell my property','contact.visit':'Ask for visit','contact.placeholder':'Explain your need...','contact.sent':'Thank you. We will contact you soon.','contact.office':'Rostom Immobilier','contact.location':'Batna, Algeria','contact.hours':'Saturday - Thursday, 9:00 - 18:00','contact.call':'Call','contact.whatsapp':'WhatsApp',
    'footer.copy':'© 2026 Rostom Immobilier','footer.text':'Minimal real estate showcase for Algeria.','breadcrumb.home':'Home','breadcrumb.properties':'Properties','breadcrumb.about':'About','breadcrumb.contact':'Contact','breadcrumb.detail':'Details',
    'admin.login':'Admin login','admin.code':'Admin code','admin.enter':'Enter','admin.back':'Back to website','admin.dashboard':'Dashboard','admin.publish':'Publish property','admin.publications':'All publications','admin.viewClient':'View website','admin.logout':'Logout','admin.export':'Export JSON','admin.import':'Import JSON','admin.title':'Publish a new property','admin.note':'All fields are optional. Empty fields are hidden from visitors.','admin.tourTitle':'360 virtual tour','admin.tourNote':'Optional. Upload equirectangular 360 panorama photos, then write room names line by line.','admin.tourImages':'360 panorama photos','admin.tourRooms':'Room names','admin.tourRoomsPlaceholder':'Salon\nKitchen\nBedroom','admin.tourUrl':'External 360 tour link','admin.uploading':'Uploading photos...','admin.savedDb':'Property published to Supabase.','admin.listNote':'Here you can see demo properties and properties added from this browser. You can delete any listing.','admin.submit':'Publish property','admin.total':'Publications','admin.sale':'Sales','admin.rent':'Rentals','admin.ready':'Wilayas ready','admin.featured':'Show in featured properties','admin.delete':'Delete','admin.none':'No property yet.','admin.saved':'Property published in this browser.','admin.deleted':'Property deleted.','admin.badCode':'Wrong code. Demo code: Rostom2026','admin.edit':'Edit','admin.editTitle':'Edit property','admin.update':'Save changes','admin.cancelEdit':'Cancel edit','admin.updated':'Property updated in this browser.','admin.updatedDb':'Property updated in Supabase.','admin.currentPhotos':'Current photos','admin.hotspotsTitle':'360 rooms & hotspots builder','admin.hotspotsHelp':'Add rooms, open a panorama, click inside it to place a hotspot, then choose the target room.','admin.addRoom':'Add room','admin.editHotspots':'Edit hotspots','admin.remove':'Remove','admin.hotspots':'hotspots','admin.noTourRooms':'No 360 rooms yet. Upload panorama photos or click Add room.','admin.clickPanorama':'Click inside the 360 viewer to select the hotspot position.','admin.closeEditor':'Close editor','admin.hotspotLabel':'Hotspot label','admin.targetRoom':'Target room','admin.selectedPoint':'Selected point','admin.addHotspot':'Add hotspot','admin.noHotspots':'No hotspots yet.','admin.choosePoint':'Click on the panorama first to choose a point.'
  },
  fr: {
    'nav.home':'Accueil','nav.properties':'Biens','nav.houses':'Maisons','nav.apartments':'Appartements','nav.contact':'Contact','nav.menu':'Menu','nav.close':'Fermer','nav.lang':'Langue','nav.cta':'Réserver une visite',
    'hero.kicker':'Batna · Toute l’Algérie','hero.buy':'Acheter.','hero.sell':'Vendre.','hero.rent':'Louer.','hero.title':'Des biens sélectionnés pour une vie moderne','hero.lead':'Une vitrine immobilière claire pour maisons, villas, appartements, terrains et locaux commerciaux partout en Algérie.','hero.view':'Explorer les biens','hero.about':'À propos de Rostom','hero.cardTitle':'69 wilayas','hero.cardText':'Les listes Wilaya et Baladiya sont prêtes pour l’Algérie. Batna inclut aussi des zones connues comme Bouaakal et Douar Eddis.',
    'search.status':'Statut','search.wilaya':'Wilaya','search.commune':'Baladiya / zone','search.query':'Recherche','search.all':'Tout','search.allAlgeria':'Toute l’Algérie','search.allAreas':'Toutes les zones','search.placeholder':'Batna, villa, terrain...','search.go':'Rechercher',
    'stats.properties':'Biens','stats.years':'Années','stats.wilayas':'Wilayas','stats.contacts':'Contact rapide','section.featured.kicker':'Biens en vedette','section.featured.title':'Sélections immobilières','section.featured.sub':'Des cartes propres avec seulement les informations utiles. Les champs vides restent cachés automatiquement.','section.featured.all':'Voir tout',
    'section.categories.kicker':'Catégories','section.categories.title':'Trouvez plus vite ce qu’il vous faut','cat.houses':'Maisons','cat.housesDesc':'Maisons familiales, duplex et immeubles résidentiels.','cat.apartments':'Appartements','cat.apartmentsDesc':'F2, F3, haut standing, vente et location.','cat.villas':'Villas','cat.villasDesc':'Villas premium, jardins, garages et grandes surfaces.','cat.estates':'Tous les biens','cat.estatesDesc':'Terrains, bureaux, locaux, projets et plus.',
    'section.about.kicker':'Pourquoi Rostom','section.about.title':'Site simple. Confiance forte.','section.about.sub':'Un client immobilier veut souvent trois choses : des photos claires, un prix clair et un contact facile.','about.one':'Aucun compte nécessaire pour les visiteurs.','about.two':'Filtres par statut, catégorie, wilaya et baladiya.','about.three':'Chaque carte est moderne, vivante et facile à lire.','about.four':'Prêt plus tard pour WhatsApp, email ou une vraie base de données.',
    'process.kicker':'Processus','process.title':'Comment le visiteur passe de la recherche à l’appel','process.1':'Définir le besoin','process.1d':'Il filtre par lieu, type et statut.','process.2':'Explorer les biens','process.2d':'Il ouvre un bien et consulte photos/détails.','process.3':'Demander une visite','process.3d':'Il vous contacte sans inscription.','process.4':'Conclure','process.4d':'Vous continuez le travail hors du site.',
    'page.properties.title':'Tous les biens','page.properties.sub':'Filtrez rapidement par statut, catégorie, wilaya et baladiya.','page.houses.title':'Maisons','page.houses.sub':'Toutes les maisons publiées par Rostom Immobilier.','page.apartments.title':'Appartements','page.apartments.sub':'Vente et location d’appartements en Algérie.','page.villas.title':'Villas','page.villas.sub':'Villas modernes, biens premium et grandes surfaces.','page.about.title':'Une agence claire, moderne et crédible.','page.about.sub':'Le but est simple : inspirer confiance rapidement.','page.contact.title':'Dites-nous ce qu’il vous faut.','page.contact.sub':'Appelez, WhatsApp, ou envoyez une demande simple.',
    'filter.category':'Catégorie','filter.quick':'Rapide','filter.sale':'Vente','filter.rent':'Location','filter.new':'Projet neuf','filter.allCat':'Toutes catégories','filter.searchPlaceholder':'Titre, ville, mot-clé...','filter.areaDisabled':'Choisissez d’abord la wilaya',
    'card.details':'Explorer','card.tour':'Visite 360°','card.contact':'Contact','card.forSale':'À vendre','card.forRent':'À louer','card.new':'Projet neuf','card.surface':'m²','card.land':'Terrain','card.rooms':'pièces','card.bedrooms':'ch.','card.baths':'sdb','card.floor':'Étage','empty':'Aucun bien trouvé. Essayez un autre filtre.',
    'detail.description':'Description','detail.features':'Caractéristiques','detail.type':'Type','detail.status':'Statut','detail.wilaya':'Wilaya','detail.commune':'Baladiya / zone','detail.address':'Adresse','detail.price':'Prix','detail.surface':'Surface bâtie','detail.land':'Surface terrain','detail.rooms':'Pièces','detail.bedrooms':'Chambres','detail.bathrooms':'Salles de bain','detail.floor':'Étage','detail.year':'Année','detail.phone':'Téléphone','detail.visit':'Demander une visite','detail.call':'Appeler','detail.notFound':'Ce bien est introuvable.','detail.virtualTour':'Visite virtuelle 360','detail.tourStart':'Voir la visite 360','detail.tourHelp':'Glissez pour regarder autour. Sur téléphone, utilisez le doigt.','detail.tourExternal':'Ouvrir la visite virtuelle','detail.tourRoom':'Pièce',
    'contact.name':'Nom','contact.phone':'Téléphone','contact.subject':'Sujet','contact.message':'Message','contact.send':'Envoyer la demande','contact.buy':'Acheter un bien','contact.rent':'Louer un bien','contact.sell':'Vendre mon bien','contact.visit':'Demander une visite','contact.placeholder':'Expliquez votre besoin...','contact.sent':'Merci. Nous vous contacterons bientôt.','contact.office':'Rostom Immobilier','contact.location':'Batna, Algérie','contact.hours':'Samedi - Jeudi, 9:00 - 18:00','contact.call':'Appeler','contact.whatsapp':'WhatsApp',
    'footer.copy':'© 2026 Rostom Immobilier','footer.text':'Vitrine immobilière minimaliste pour l’Algérie.','breadcrumb.home':'Accueil','breadcrumb.properties':'Biens','breadcrumb.about':'À propos','breadcrumb.contact':'Contact','breadcrumb.detail':'Détails',
    'admin.login':'Connexion admin','admin.code':'Code admin','admin.enter':'Entrer','admin.back':'Retour au site','admin.dashboard':'Tableau de bord','admin.publish':'Publier un bien','admin.publications':'Toutes les publications','admin.viewClient':'Voir le site','admin.logout':'Déconnexion','admin.export':'Exporter JSON','admin.import':'Importer JSON','admin.title':'Publier un nouveau bien','admin.note':'Tous les champs sont optionnels. Les champs vides ne s’affichent pas aux visiteurs.','admin.tourTitle':'Visite virtuelle 360','admin.tourNote':'Optionnel. Téléversez des photos panorama 360 équirectangulaires, puis écrivez les noms des pièces ligne par ligne.','admin.tourImages':'Photos panorama 360','admin.tourRooms':'Noms des pièces','admin.tourRoomsPlaceholder':'Salon\nCuisine\nChambre','admin.tourUrl':'Lien externe visite 360','admin.uploading':'Téléversement des photos...','admin.savedDb':'Bien publié dans Supabase.','admin.listNote':'Ici vous voyez les biens de démo et les biens ajoutés depuis ce navigateur. Vous pouvez supprimer n’importe quelle annonce.','admin.submit':'Publier le bien','admin.total':'Publications','admin.sale':'Ventes','admin.rent':'Locations','admin.ready':'Wilayas prêtes','admin.featured':'Afficher dans les biens en vedette','admin.delete':'Supprimer','admin.none':'Aucun bien pour le moment.','admin.saved':'Bien publié dans ce navigateur.','admin.deleted':'Bien supprimé.','admin.badCode':'Code incorrect. Code de démonstration : Rostom2026','admin.edit':'Modifier','admin.editTitle':'Modifier le bien','admin.update':'Enregistrer','admin.cancelEdit':'Annuler la modification','admin.updated':'Bien modifié dans ce navigateur.','admin.updatedDb':'Bien modifié dans Supabase.','admin.currentPhotos':'Photos actuelles','admin.hotspotsTitle':'Créateur de pièces 360 et hotspots','admin.hotspotsHelp':'Ajoutez des pièces, ouvrez un panorama, cliquez dedans pour placer un hotspot, puis choisissez la pièce cible.','admin.addRoom':'Ajouter une pièce','admin.editHotspots':'Modifier hotspots','admin.remove':'Retirer','admin.hotspots':'hotspots','admin.noTourRooms':'Aucune pièce 360. Téléversez des panoramas ou cliquez sur Ajouter une pièce.','admin.clickPanorama':'Cliquez dans la vue 360 pour sélectionner la position du hotspot.','admin.closeEditor':'Fermer','admin.hotspotLabel':'Nom du hotspot','admin.targetRoom':'Pièce cible','admin.selectedPoint':'Point sélectionné','admin.addHotspot':'Ajouter hotspot','admin.noHotspots':'Aucun hotspot.','admin.choosePoint':'Cliquez d’abord sur le panorama pour choisir un point.'
  },
  ar: {
    'nav.home':'الرئيسية','nav.properties':'العقارات','nav.houses':'منازل','nav.apartments':'شقق','nav.contact':'تواصل','nav.menu':'القائمة','nav.close':'إغلاق','nav.lang':'اللغة','nav.cta':'احجز زيارة',
    'hero.kicker':'باتنة · كل الجزائر','hero.buy':'شراء.','hero.sell':'بيع.','hero.rent':'كراء.','hero.title':'عقارات مختارة لحياة عصرية','hero.lead':'واجهة عقارية نظيفة للمنازل، الفيلات، الشقق، الأراضي والمحلات عبر الجزائر.','hero.view':'تصفح العقارات','hero.about':'عن روستم','hero.cardTitle':'69 ولاية','hero.cardText':'قوائم الولايات والبلديات جاهزة للجزائر. وفي باتنة أضفنا أيضا مناطق معروفة مثل بوعقال ودوار الديس.',
    'search.status':'الحالة','search.wilaya':'الولاية','search.commune':'البلدية / الحي','search.query':'بحث','search.all':'الكل','search.allAlgeria':'كل الجزائر','search.allAreas':'كل المناطق','search.placeholder':'باتنة، فيلا، أرض...','search.go':'بحث',
    'stats.properties':'عقارات','stats.years':'سنوات','stats.wilayas':'ولايات','stats.contacts':'تواصل سريع','section.featured.kicker':'عقارات مميزة','section.featured.title':'مختارات العقارات','section.featured.sub':'بطاقات نظيفة تعرض المعلومات المهمة فقط. الحقول الفارغة لا تظهر تلقائيا.','section.featured.all':'عرض الكل',
    'section.categories.kicker':'الفئات','section.categories.title':'اعثر على ما تحتاجه بسرعة','cat.houses':'منازل','cat.housesDesc':'منازل عائلية، دوبلكس وبنايات سكنية.','cat.apartments':'شقق','cat.apartmentsDesc':'F2، F3، راقية، للبيع والكراء.','cat.villas':'فيلات','cat.villasDesc':'فيلات فاخرة، حدائق، مرائب ومساحات كبيرة.','cat.estates':'كل العقارات','cat.estatesDesc':'أراضي، مكاتب، محلات، مشاريع وأكثر.',
    'section.about.kicker':'لماذا روستم','section.about.title':'موقع بسيط. ثقة قوية.','section.about.sub':'زبون العقار يريد غالبا ثلاث أشياء: صور واضحة، سعر واضح، وطريقة تواصل سهلة.','about.one':'لا يحتاج الزائر لإنشاء حساب.','about.two':'فلترة حسب الحالة، الفئة، الولاية والبلدية.','about.three':'بطاقات حديثة، حية وسهلة القراءة.','about.four':'جاهز لاحقا للربط مع واتساب، الإيميل أو قاعدة بيانات حقيقية.',
    'process.kicker':'الخطوات','process.title':'كيف ينتقل الزائر من البحث إلى الاتصال','process.1':'تحديد الحاجة','process.1d':'يفلتر حسب المكان، النوع والحالة.','process.2':'تصفح العقارات','process.2d':'يفتح العقار ويرى الصور والتفاصيل.','process.3':'طلب زيارة','process.3d':'يتواصل معك بدون تسجيل.','process.4':'إتمام الصفقة','process.4d':'تكمل معه العمل خارج الموقع.',
    'page.properties.title':'كل العقارات','page.properties.sub':'فلتر بسرعة حسب الحالة، الفئة، الولاية والبلدية.','page.houses.title':'منازل','page.houses.sub':'كل المنازل المنشورة في روستم للعقارات.','page.apartments.title':'شقق','page.apartments.sub':'بيع وكراء الشقق عبر الجزائر.','page.villas.title':'فيلات','page.villas.sub':'فيلات عصرية، عقارات راقية ومساحات كبيرة.','page.about.title':'وكالة واضحة، عصرية وموثوقة.','page.about.sub':'الهدف بسيط: تجعل الناس يثقون بك بسرعة.','page.contact.title':'أخبرنا ماذا تحتاج.','page.contact.sub':'اتصل، واتساب، أو أرسل طلبا بسيطا.',
    'filter.category':'الفئة','filter.quick':'سريع','filter.sale':'بيع','filter.rent':'كراء','filter.new':'مشروع جديد','filter.allCat':'كل الفئات','filter.searchPlaceholder':'عنوان، مدينة، كلمة...','filter.areaDisabled':'اختر الولاية أولا',
    'card.details':'استكشف','card.tour':'جولة 360°','card.contact':'تواصل','card.forSale':'للبيع','card.forRent':'للكراء','card.new':'مشروع جديد','card.surface':'م²','card.land':'الأرض','card.rooms':'غرف','card.bedrooms':'غ.نوم','card.baths':'حمام','card.floor':'الطابق','empty':'لا توجد عقارات. جرّب فلتر آخر.',
    'detail.description':'الوصف','detail.features':'المميزات','detail.type':'النوع','detail.status':'الحالة','detail.wilaya':'الولاية','detail.commune':'البلدية / الحي','detail.address':'العنوان','detail.price':'السعر','detail.surface':'المساحة المبنية','detail.land':'مساحة الأرض','detail.rooms':'الغرف','detail.bedrooms':'غرف النوم','detail.bathrooms':'الحمامات','detail.floor':'الطابق','detail.year':'السنة','detail.phone':'الهاتف','detail.visit':'طلب زيارة','detail.call':'اتصال','detail.notFound':'هذا العقار غير موجود.','detail.virtualTour':'جولة افتراضية 360','detail.tourStart':'عرض جولة 360','detail.tourHelp':'اسحب للنظر حولك. في الهاتف استعمل إصبعك.','detail.tourExternal':'فتح الجولة الافتراضية','detail.tourRoom':'غرفة',
    'contact.name':'الاسم','contact.phone':'الهاتف','contact.subject':'الموضوع','contact.message':'الرسالة','contact.send':'إرسال الطلب','contact.buy':'شراء عقار','contact.rent':'كراء عقار','contact.sell':'بيع عقاري','contact.visit':'طلب زيارة','contact.placeholder':'اشرح حاجتك...','contact.sent':'شكرا. سنتواصل معك قريبا.','contact.office':'روستم للعقارات','contact.location':'باتنة، الجزائر','contact.hours':'السبت - الخميس، 9:00 - 18:00','contact.call':'اتصال','contact.whatsapp':'واتساب',
    'footer.copy':'© 2026 روستم للعقارات','footer.text':'واجهة عقارية بسيطة للجزائر.','breadcrumb.home':'الرئيسية','breadcrumb.properties':'العقارات','breadcrumb.about':'عن الوكالة','breadcrumb.contact':'تواصل','breadcrumb.detail':'التفاصيل',
    'admin.login':'دخول الإدارة','admin.code':'كود الإدارة','admin.enter':'دخول','admin.back':'العودة للموقع','admin.dashboard':'لوحة التحكم','admin.publish':'نشر عقار','admin.publications':'كل المنشورات','admin.viewClient':'عرض الموقع','admin.logout':'خروج','admin.export':'تصدير JSON','admin.import':'استيراد JSON','admin.title':'نشر عقار جديد','admin.note':'كل الحقول اختيارية. الحقول الفارغة لا تظهر للزوار.','admin.tourTitle':'جولة افتراضية 360','admin.tourNote':'اختياري. ارفع صور بانوراما 360، ثم اكتب أسماء الغرف كل اسم في سطر.','admin.tourImages':'صور بانوراما 360','admin.tourRooms':'أسماء الغرف','admin.tourRoomsPlaceholder':'الصالون\nالمطبخ\nغرفة النوم','admin.tourUrl':'رابط خارجي لجولة 360','admin.uploading':'جاري رفع الصور...','admin.savedDb':'تم نشر العقار في Supabase.','admin.listNote':'هنا تظهر عقارات التجربة والعقارات المضافة من هذا المتصفح. يمكنك حذف أي إعلان.','admin.submit':'نشر العقار','admin.total':'منشورات','admin.sale':'بيع','admin.rent':'كراء','admin.ready':'ولايات جاهزة','admin.featured':'إظهار في العقارات المميزة','admin.delete':'حذف','admin.none':'لا توجد منشورات بعد.','admin.saved':'تم نشر العقار في هذا المتصفح.','admin.deleted':'تم حذف العقار.','admin.badCode':'الكود غير صحيح. كود التجربة: Rostom2026','admin.edit':'تعديل','admin.editTitle':'تعديل العقار','admin.update':'حفظ التغييرات','admin.cancelEdit':'إلغاء التعديل','admin.updated':'تم تعديل العقار في هذا المتصفح.','admin.updatedDb':'تم تعديل العقار في Supabase.','admin.currentPhotos':'الصور الحالية','admin.hotspotsTitle':'إدارة غرف 360 والنقاط التفاعلية','admin.hotspotsHelp':'أضف الغرف، افتح صورة 360، اضغط داخلها لتحديد النقطة، ثم اختر الغرفة الهدف.','admin.addRoom':'إضافة غرفة','admin.editHotspots':'تعديل النقاط','admin.remove':'حذف','admin.hotspots':'نقاط','admin.noTourRooms':'لا توجد غرف 360 بعد. ارفع صور بانوراما أو اضغط إضافة غرفة.','admin.clickPanorama':'اضغط داخل عارض 360 لاختيار مكان النقطة.','admin.closeEditor':'إغلاق المحرر','admin.hotspotLabel':'اسم النقطة','admin.targetRoom':'الغرفة الهدف','admin.selectedPoint':'النقطة المحددة','admin.addHotspot':'إضافة النقطة','admin.noHotspots':'لا توجد نقاط بعد.','admin.choosePoint':'اضغط أولا على صورة 360 لاختيار نقطة.'
  }
};

function currentLang(){ return localStorage.getItem(LANG_KEY) || DEFAULT_LANG; }
function t(key){ return (I18N[currentLang()] && I18N[currentLang()][key]) || I18N.en[key] || key; }
function applyLanguage(){
  const lang = currentLang();
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  document.body.classList.toggle('is-rtl', lang === 'ar');
  document.querySelectorAll('[data-i18n]').forEach(el => { el.textContent = t(el.dataset.i18n); });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => { el.placeholder = t(el.dataset.i18nPlaceholder); });
  document.querySelectorAll('.language-select').forEach(sel => { sel.value = lang; });
}
function bindLanguageSelectors(){
  document.querySelectorAll('.language-select').forEach(sel => {
    sel.value = currentLang();
    sel.addEventListener('change', () => { localStorage.setItem(LANG_KEY, sel.value); location.reload(); });
  });
}
